title_en = "Solo"
title_sk = "Solo"
order = 1
description_en = '''
Water level, a symbol of infinity, has been attracting the eye of a mankind for centuries.
Apartment houses with their water edge composition offer a mixture of holiday like feeling and everyday life in the capital city.
Hotel resort and retail outlets built on the water create a contrast to nearby busy city rush, enabling its visitors a total relief from working stress.
What a delightful mixture, mixed urban zone.
'''
description_sk = '''
'''