title_en = "Zelenečská"
title_sk = "Zelenečská"
order = 1
description_en = '''
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = "povodny stav"
description_en = ""
description_sk = "povodný stav - podorys"
url = "povodny-podorys"

[[images]]
title_en = ""
title_sk = "navrh"
description_en = ""
description_sk = "návrh - podorys"
url = "navrh-podorys"