title_en = "Zelenečská"
title_sk = "Zelenečská"
order = 1
description_en = '''
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = "povodny stav"
description_en = ""
description_sk = "povodný stav - podorys"
url = "povodny-podorys"

[[images]]
title_en = ""
title_sk = "navrh"
description_en = ""
description_sk = "návrh - podorys"
url = "navrh-podorys"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-11-44"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-11-48"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-11-57"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-02"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-03"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-04-1"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-04"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-09"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-10-1"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-10"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-15"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-17"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-19"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-39"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-42"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-45"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-48-1"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-48"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-12-51"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-13-12"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-13-13"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-13-14"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-13-16"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2016-12-07-byt-zelenecska-13-17"