title_en = "New age apartment"
title_sk = "Nová doba"
order = 1
description_en = '''
The things I like about this apartment are details. The bathroom with glass walls, the white kitchen with the black counter in the middle, the bedroom in Japanese style and the yellow balcony. Vivid colours and young soul of the flat for one or two.
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch12a"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch12b"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch12c"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch12d"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch12e"
