title_en = "W5"
title_sk = "W5"
order = 1
description_en = '''
W5 is a city hotel with a restaurant, two galleries (one open-air and one with a glass roof) in a busy suburb of Vienna.
An orange cube slightly protruding to the space is simply a coffee bar or a vista point with a fabulous view of the city life.
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "JPG-podorysy-pohlad-rezy"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "JPG-vizosky"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch2a"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch2b"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch2c"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch2d"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch2e"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch2f"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "w5"
