title_en = "Barnova"
title_sk = "Barnova"
order = 1
description_en = '''
Best house ever.
'''
description_sk = '''
Best house ever.
'''

[[images]]
title_en = "Dom Barnova"
title_sk = "Dom Barnova"
description_en = "popisek 1"
description_sk = "popisek 1"
url = "alt1"
main = true

[[images]]
title_en = "Dom Barnova"
title_sk = "Dom Barnova"
description_en = "popisek 2"
description_sk = "popisek 2"
url = "alt2"