title_en = "Bed"
title_sk = "Postiel"
order = 1
description_en = '''
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "ybed"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "ybed1"