title_en = "W5"
title_sk = "W5"
order = 1
description_en = '''
W5 is a city hotel with a restaurant, two galleries (one open-air and one with a glass roof) in a busy suburb of Vienna.
An orange cube slightly protruding to the space is simply a coffee bar or a vista point with a fabulous view of the city life.
'''
description_sk = '''
'''