title_en = "Sideboard"
title_sk = "Príborník"
order = 1
description_en = '''
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2017-01-03-12-27"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2017-01-03-12-28"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "2017-01-03-12-29"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "ykrina1"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "ykrina2"