title_en = "Nešporova Entrance"
title_sk = "Nešporova Prístrešok"
order = 1
category = ["exterior-design"]
description_en = '''
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "757-5755-IMG"
