title_en = "Lifeline"
title_sk = "Lifeline"
order = 1
description_en = '''
Lifeline shops are unique for their concept. They are unifying in basic shapes, still different in a variety of details. The most significant and eye catching is the wall behind the cash desk.
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "759-5974-IMG"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "759-5984-IMG"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "DSC09917.jpg"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "P1050028"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "P1090218"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "P1110490"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "P1110503"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "P1110504"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "P1110505"