title_en = "Lifeline"
title_sk = "Lifeline"
order = 1
description_en = '''
Lifeline shops are unique for their concept. They are unifying in basic shapes, still different in a variety of details. The most significant and eye catching is the wall behind the cash desk.
'''
description_sk = '''
'''