title_en = "Solo"
title_sk = "Solo"
order = 1
description_en = '''
Water level, a symbol of infinity, has been attracting the eye of a mankind for centuries.
Apartment houses with their water edge composition offer a mixture of holiday like feeling and everyday life in the capital city.
Hotel resort and retail outlets built on the water create a contrast to nearby busy city rush, enabling its visitors a total relief from working stress.
What a delightful mixture, mixed urban zone.
'''
description_sk = '''
'''

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "A-situacia-2000-sirsie-vztahy"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "B-situacia-1000-zastavovacia"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "M-perspektivy-acad"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "O-vizualizacie"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3a"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3b"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3c"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3d"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3e"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3f"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3g"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3h"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "picarch3i"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "solo-1"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "solo-2"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "solo-3"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "solo-4"

[[images]]
title_en = ""
title_sk = ""
description_en = ""
description_sk = ""
url = "solo-5"
